services:
  app:
    build:
      dockerfile: Dockerfile.dev
    container_name: react-docker-template-dev
    env_file:
      - .env.dev
    ports:
      - "${VITE_EXPOSED_HOST}:${VITE_EXPOSED_PORT}:3000"
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true